var_eg = 1.o 2.o 3.o
eg = exempli_gratia
ie = id_est
var2 := $(var_eg)
# simply expanded variables
# @ suppresses, commands, e.g. @cmd, @ suppresses echoing the cmd

print:
	echo $(var_eg)
	echo $(var2)
	@echo should be suppressed

employee_oop:
	gcc -o em -Wextra -Wall employee_oop.c 